"""add all models

Revision ID: c5d026218595
Revises: 
Create Date: 2026-09-26 17:20:55.137953

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c5d026218595'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('references',
    sa.Column('municipality', sa.String(length=100), nullable=False),
    sa.Column('service_name', sa.String(length=255), nullable=False),
    sa.Column('value_type', sa.String(length=50), nullable=False),
    sa.Column('value', sa.Numeric(precision=12, scale=4), nullable=False),
    sa.Column('valid_from', sa.Date(), nullable=True),
    sa.Column('valid_to', sa.Date(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_references_municipality'), 'references', ['municipality'], unique=False)
    op.create_table('users',
    sa.Column('max_user_id', sa.BigInteger(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_max_user_id'), 'users', ['max_user_id'], unique=True)
    op.create_table('receipts',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('period_month', sa.String(length=20), nullable=True),
    sa.Column('period_year', sa.Integer(), nullable=True),
    sa.Column('file_path', sa.String(length=500), nullable=True),
    sa.Column('raw_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('total_with_insurance', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('total_without_insurance', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('check_results',
    sa.Column('receipt_id', sa.Integer(), nullable=False),
    sa.Column('has_errors', sa.Boolean(), nullable=False),
    sa.Column('errors', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('checked_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['receipt_id'], ['receipts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('receipt_id')
    )
    op.create_table('coefficients',
    sa.Column('receipt_id', sa.Integer(), nullable=False),
    sa.Column('service_name', sa.String(length=255), nullable=True),
    sa.Column('coefficient', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('excess_amount', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['receipt_id'], ['receipts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('meter_infos',
    sa.Column('receipt_id', sa.Integer(), nullable=False),
    sa.Column('provider_code', sa.String(length=50), nullable=True),
    sa.Column('service_name', sa.String(length=255), nullable=True),
    sa.Column('meter_type', sa.String(length=20), nullable=True),
    sa.Column('meter_number', sa.String(length=50), nullable=True),
    sa.Column('verification_date', sa.String(length=20), nullable=True),
    sa.Column('previous_reading', sa.Numeric(precision=12, scale=3), nullable=True),
    sa.Column('current_reading', sa.Numeric(precision=12, scale=3), nullable=True),
    sa.Column('consumption', sa.Numeric(precision=12, scale=3), nullable=True),
    sa.Column('norm_residential', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('norm_odn', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('total_residential', sa.Numeric(precision=12, scale=3), nullable=True),
    sa.Column('total_odn', sa.Numeric(precision=12, scale=3), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['receipt_id'], ['receipts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('recalculations',
    sa.Column('receipt_id', sa.Integer(), nullable=False),
    sa.Column('service_name', sa.String(length=255), nullable=True),
    sa.Column('reason', sa.String(length=500), nullable=True),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['receipt_id'], ['receipts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('service_charges',
    sa.Column('receipt_id', sa.Integer(), nullable=False),
    sa.Column('section', sa.String(length=50), nullable=True),
    sa.Column('service_name', sa.String(length=255), nullable=True),
    sa.Column('volume', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('unit', sa.String(length=20), nullable=True),
    sa.Column('tariff', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('benefit', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('recalculation', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('debt_start', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('paid', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('total', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['receipt_id'], ['receipts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('service_charges')
    op.drop_table('recalculations')
    op.drop_table('meter_infos')
    op.drop_table('coefficients')
    op.drop_table('check_results')
    op.drop_table('receipts')
    op.drop_index(op.f('ix_users_max_user_id'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_references_municipality'), table_name='references')
    op.drop_table('references')
    # ### end Alembic commands ###
